name: Deploy Laravel Backend to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: self-hosted # Uses your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Local Vendor Folder
        run: |
          Copy-Item -Path "C:\Users\Operations Lateef\work\wordcast_app\WordCast_LIVE\Wordcast_website\backend\vendor" -Destination .\vendor -Recurse -Force

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Keep this as / as it deploys to the root of the FTP account
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            .env.example
            .env
            tests/**
